### show app version

GET {{url}}/info
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.6)
Accept-Encoding: br,deflate,gzip,x-gzip
Authorization: Bearer {{$token}}

### show sql

GET {{url}}/db
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.6)
Accept-Encoding: br,deflate,gzip,x-gzip
Authorization: Bearer {{token}}

### init db sql

POST {{url}}/db
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.6)
Accept-Encoding: br,deflate,gzip,x-gzip
Authorization: Bearer {{token}}

{"update":false}

### show list versions

GET {{url}}/db/versions
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.6)
Accept-Encoding: br,deflate,gzip,x-gzip
Authorization: Bearer {{token}}

### show actual version

GET {{url}}/db/actualVersion
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.6)
Accept-Encoding: br,deflate,gzip,x-gzip
Authorization: Bearer {{token}}

### show list users

GET {{url}}/db/users
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.6)
Accept-Encoding: br,deflate,gzip,x-gzip
Authorization: Bearer {{token}}

### get user

GET {{url}}/db/user?login=lukasSyk
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.6)
Accept-Encoding: br,deflate,gzip,x-gzip
Authorization: Bearer {{token}}

### create user

POST {{url}}/db/user
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.6)
Accept-Encoding: br,deflate,gzip,x-gzip
Authorization: Bearer {{token}}

{"login":"inovatika"}


### update user

PUT {{url}}/db/user
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.6)
Accept-Encoding: br,deflate,gzip,x-gzip
Authorization: Bearer {{token}}

{"userId":"17","login":"lukaSyk"}

### get digitalObjects
GET {{url}}/db/objects?orderBy=datum&orderSort=asc&instance=k7
Authorization: Bearer {{token}}


### get digital Object
GET {{url}}/db/object?limit=1&offset=5
Authorization: Bearer {{token}}

### get all batches with type
GET {{url}}/db/batches?type=SINGLE
Authorization: Bearer {{token}}

### get batches
GET {{url}}/db/batch?limit=1&offset=4
Authorization: Bearer {{token}}

### get Image
GET {{url}}/object/image?pid={{uuid}}&instance=k7
Authorization: Bearer {{token}}

### get Alto
GET {{url}}/object/alto?pid={{uuid3}}&instance=k7
Authorization: Bearer {{token}}

### get Ocr
GET {{url}}/object/ocr?pid={{uuid3}}&instance=k7
Authorization: Bearer {{token}}

### update Alto
POST {{url}}/object/alto
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.6)
Accept-Encoding: br,deflate,gzip,x-gzip
Authorization: Bearer {{token}}

{"login":"inovatika","pid":"{{uuid}}", "data":"{{data}}"}

### generate Pero
POST {{url}}/object/pero
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.6)
Accept-Encoding: br,deflate,gzip,x-gzip
Authorization: Bearer {{token}}

{"pid":"uuid:65cb5124-6af4-4b50-acd0-0cbf0867f968","priority":"MEDIUM", "instance":"k7"}

### set version as accepted
POST {{url}}/object/stateAccepted
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.6)
Accept-Encoding: br,deflate,gzip,x-gzip
Authorization: Bearer {{token}}

{"id":{{digitalObjectId}},"login":"inovatika"}

### set version as rejected
POST {{url}}/object/stateRejected
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.6)
Accept-Encoding: br,deflate,gzip,x-gzip
Authorization: Bearer {{token}}

{"id":{{digitalObjectId}},"login":"inovatika"}

### upload version to Kramerius
POST {{url}}/object/uploadKramerius
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.6)
Accept-Encoding: br,deflate,gzip,x-gzip
Authorization: Bearer {{token}}

{"id":{{digitalObjectId}},"login":"inovatika"}

### get object information
GET {{url}}/object/objectInformation?pid={{uuid3}}&instance=k7
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.6)
Accept-Encoding: br,deflate,gzip,x-gzip
Authorization: Bearer {{token}}








