package cz.inovatika.altoEditor.db.empireDb;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import org.apache.empire.data.DataMode;
import org.apache.empire.data.DataType;
import org.apache.empire.db.DBCmdType;
import org.apache.empire.db.DBColumn;
import org.apache.empire.db.DBCommand;
import org.apache.empire.db.DBDatabase;
import org.apache.empire.db.DBDatabaseDriver;
import org.apache.empire.db.DBRecord;
import org.apache.empire.db.DBSQLScript;
import org.apache.empire.db.DBTable;
import org.apache.empire.db.DBTableColumn;
import org.apache.empire.db.exceptions.QueryFailedException;
import org.apache.empire.db.postgresql.DBDatabaseDriverPostgreSQL;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * Represents the database configuration and schema definition for the AltoEditor application.
 * This class extends {@code DBDatabase} and provides the database structure, table definitions,
 * and initialization logic required for managing the schema.
 */
@Deprecated
public class AltoEditorDatabaseV2 extends DBDatabase {

    private static final long serialVersionUID = 1L;
    private static final Logger LOG = LogManager.getLogger(AltoEditorDatabaseV2.class.getName());
    /** the schema version */
    public static final int VERSION = 2;

    public final VersionTable tableVersion = new VersionTable(this);
    public final BatchTable tableBatch = new BatchTable(this);
    public final UserTable tableUser = new UserTable(this);
    public final DigitalObjectTable tableDigitalObject = new DigitalObjectTable(this);

    public static class VersionTable extends DBTable {

        private static final long serialVersionUID = 1L;

        public final DBTableColumn id;
        public final DBTableColumn datum;
        public final DBTableColumn version;

        public VersionTable(DBDatabase db) {
            super("VERSION", db);
            id = addColumn("ID", DataType.AUTOINC, 0, DataMode.AutoGenerated, "VERSION_ID_SEQ");
            datum = addColumn("DATUM", DataType.TIMESTAMP, 0, true);
            version = addColumn("VERSION", DataType.INTEGER, 0, true);
            setPrimaryKey(id);
        }
    }

    public static class BatchTable extends DBTable {

        private static final long serialVersionUID = 1L;

        public final DBTableColumn id;
        public final DBTableColumn pid;
        public final DBTableColumn createDate;
        public final DBTableColumn updateDate;
        public final DBTableColumn state;
        public final DBTableColumn subState;
        public final DBTableColumn priority;
        public final DBTableColumn type;
        public final DBTableColumn instance;
        public final DBTableColumn objectId;
        public final DBTableColumn estimateItemNumber;
        public final DBTableColumn log;

        public BatchTable(DBDatabase db) {
            super("BATCH", db);
            id = addColumn("ID", DataType.AUTOINC, 0, DataMode.AutoGenerated, "BATCH_ID_SEQ");
            pid = addColumn("PID", DataType.TEXT, 100, false);
            createDate = addColumn("CREATEDATE", DataType.TIMESTAMP, 0, true);
            updateDate = addColumn("UPDATEDATE", DataType.TIMESTAMP, 0, true);
            state = addColumn("STATE", DataType.TEXT, 20, true);
            subState = addColumn("SUBSTATE", DataType.TEXT, 20, false);
            priority = addColumn("PRIORITY", DataType.TEXT, 100, true);
            type = addColumn("TYPE", DataType.TEXT, 20, false);
            instance = addColumn("INSTANCE", DataType.TEXT, 20, false);;
            objectId = addColumn("OBJECTID", DataType.INTEGER, 2000, false);
            estimateItemNumber = addColumn("ESTIMATEITEMNUMBER", DataType.INTEGER, 0, false);
            log = addColumn("LOG", DataType.CLOB, 0, false);
            setPrimaryKey(id);
            addIndex(String.format("%s_IDX", getName()), false, new DBColumn[] { id, pid, state});
        }
    }

    public static final class UserTable extends DBTable {

        private static final long serialVersionUID = 1L;

        public final DBTableColumn id;
        public final DBTableColumn login;

        public UserTable(DBDatabase db) {
            super("USERS", db);
            id = addColumn("ID", DataType.AUTOINC, 0, DataMode.AutoGenerated, "USERS_ID_SEQ");
            id.setBeanPropertyName("id");
            login = addColumn("LOGIN", DataType.TEXT, 255, true);
            login.setBeanPropertyName("login");
            setPrimaryKey(id);
            addIndex(String.format("%s_%s_IDX", getName(), login.getName()), true, new DBColumn[] { login });
        }

    }

    public class DigitalObjectTable extends DBTable {

        private static final long serialVersionUID = 1L;

        public final DBTableColumn id;
        public final DBTableColumn rUserId;
        public final DBTableColumn instance;
        public final DBTableColumn pid;
        public final DBTableColumn version;
        public final DBTableColumn datum;
        public final DBTableColumn state;

        public DigitalObjectTable(DBDatabase db) {
            super("DIGITALOBJECT", db);
            id = addColumn("ID", DataType.AUTOINC, 0, DataMode.AutoGenerated, "DIGITALOBJECT_ID_SEQ");
            rUserId = addColumn("RUSERID", DataType.INTEGER, 0, true);
            instance = addColumn("INSTANCE", DataType.TEXT, 2000, true);
            pid = addColumn("PID", DataType.TEXT, 2000, true);
            version = addColumn("VERSION", DataType.TEXT, 255, true);
            datum = addColumn("DATUM", DataType.TIMESTAMP, 0, true);
            state = addColumn("STATE", DataType.TEXT, 20, true);

            setPrimaryKey(id);
            addIndex(String.format("%s_%s_IDX", getName(), rUserId.getName()), true, new DBColumn[] { rUserId });
        }

    }

    public AltoEditorDatabaseV2() {
        addRelation(tableDigitalObject.rUserId.referenceOn(tableUser.id));
    }

    public static int upgradeToVersion3(int currentSchemaVersion, Connection conn, EmpireConfiguration conf) throws SQLException {
        if (currentSchemaVersion < VERSION) {
            currentSchemaVersion = AltoEditorDatabaseV1.upgradeToVersion2(currentSchemaVersion, conn, conf);
        }
        if (currentSchemaVersion > VERSION) {
            // ignore higher versions
            return currentSchemaVersion;
        } else if (currentSchemaVersion != VERSION) {
            throw new SQLException("Cannot upgrade from schema version " + currentSchemaVersion);
        }

        AltoEditorDatabaseV3 schema = new AltoEditorDatabaseV3();
        try {
            schema.open(conf.getDriver(), conn);
            upgradeDdl(schema, conn);
            LOG.info("Upgrading AltoEditor schema from version {}.", currentSchemaVersion);
            int schemaVersion = schema.initVersion(conn);

            conn.commit();
            return schemaVersion;
        } finally {
            schema.close(conn);
        }
    }

    private static void upgradeDdl(AltoEditorDatabaseV3 schema, Connection conn) throws SQLException {
        try {
            conn.setAutoCommit(true);

            DBDatabaseDriver driver = schema.getDriver();
            DBSQLScript script = new DBSQLScript();

            driver.getDDLScript(DBCmdType.CREATE, schema.tableDigitalObject.label, script);
            driver.getDDLScript(DBCmdType.CREATE, schema.tableDigitalObject.parentPath, script);
            driver.getDDLScript(DBCmdType.CREATE, schema.tableDigitalObject.parentLabel, script);
            driver.getDDLScript(DBCmdType.CREATE, schema.tableDigitalObject.lock, script);

            LOG.debug(script.toString());
            script.executeAll(driver, conn);
        } finally {
            conn.setAutoCommit(false);
        }
    }

    int initVersion(Connection conn) {
        AltoEditorDatabaseV2 db = this;
        DBRecord dbRecord = new DBRecord();

        dbRecord.create(db.tableVersion);
        dbRecord.setValue(db.tableVersion.version, VERSION);
        dbRecord.setValue(db.tableVersion.datum, new java.sql.Timestamp(System.currentTimeMillis()));
        dbRecord.update(conn);
        return VERSION;
    }
}
