package cz.inovatika.altoEditor.db.empireDb;

import java.sql.Connection;
import java.sql.SQLException;
import org.apache.empire.data.DataMode;
import org.apache.empire.data.DataType;
import org.apache.empire.db.DBColumn;
import org.apache.empire.db.DBCommand;
import org.apache.empire.db.DBDatabase;
import org.apache.empire.db.DBDatabaseDriver;
import org.apache.empire.db.DBRecord;
import org.apache.empire.db.DBSQLScript;
import org.apache.empire.db.DBTable;
import org.apache.empire.db.DBTableColumn;
import org.apache.empire.db.exceptions.QueryFailedException;
import org.apache.empire.db.postgresql.DBDatabaseDriverPostgreSQL;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * Represents the database configuration and schema definition for the AltoEditor application.
 * This class extends {@code DBDatabase} and provides the database structure, table definitions,
 * and initialization logic required for managing the schema.
 */
public class AltoEditorDatabase extends DBDatabase {

    private static final long serialVersionUID = 1L;
    private static final Logger LOG = LogManager.getLogger(AltoEditorDatabase.class.getName());
    /** the schema version */
    public static final int VERSION = 6;

    public final VersionTable tableVersion = new VersionTable(this);
    public final BatchTable tableBatch = new BatchTable(this);
    public final UserTable tableUser = new UserTable(this);
    public final DigitalObjectTable tableDigitalObject = new DigitalObjectTable(this);

    public static class VersionTable extends DBTable {

        private static final long serialVersionUID = 1L;

        public final DBTableColumn id;
        public final DBTableColumn datum;
        public final DBTableColumn version;

        public VersionTable(DBDatabase db) {
            super("VERSION", db);
            id = addColumn("ID", DataType.AUTOINC, 0, DataMode.AutoGenerated, "VERSION_ID_SEQ");
            datum = addColumn("DATUM", DataType.TIMESTAMP, 0, true);
            version = addColumn("VERSION", DataType.INTEGER, 0, true);
            setPrimaryKey(id);
        }
    }

    public static class BatchTable extends DBTable {

        private static final long serialVersionUID = 1L;

        public final DBTableColumn id;
        public final DBTableColumn pid;
        public final DBTableColumn createDate;
        public final DBTableColumn updateDate;
        public final DBTableColumn state;
        public final DBTableColumn subState;
        public final DBTableColumn priority;
        public final DBTableColumn type;
        public final DBTableColumn instance;
        public final DBTableColumn objectId;
        public final DBTableColumn estimateItemNumber;
        public final DBTableColumn log;
        public final DBTableColumn ocrEngine;

        public BatchTable(DBDatabase db) {
            super("BATCH", db);
            id = addColumn("ID", DataType.AUTOINC, 0, DataMode.AutoGenerated, "BATCH_ID_SEQ");
            pid = addColumn("PID", DataType.TEXT, 100, false);
            createDate = addColumn("CREATE_DATE", DataType.TIMESTAMP, 0, true);
            updateDate = addColumn("UPDATE_DATE", DataType.TIMESTAMP, 0, true);
            state = addColumn("STATE", DataType.TEXT, 20, true);
            subState = addColumn("SUB_STATE", DataType.TEXT, 20, false);
            priority = addColumn("PRIORITY", DataType.TEXT, 100, true);
            type = addColumn("TYPE", DataType.TEXT, 20, false);
            instance = addColumn("INSTANCE", DataType.TEXT, 20, false);;
            objectId = addColumn("OBJECT_ID", DataType.INTEGER, 2000, false);
            estimateItemNumber = addColumn("ESTIMATE_ITEM_NUMBER", DataType.INTEGER, 0, false);
            log = addColumn("LOG", DataType.CLOB, 0, false);
            ocrEngine = addColumn("OCR_ENGINE", DataType.INTEGER, 0, false);
            setPrimaryKey(id);
            addIndex(String.format("%s_IDX", getName()), false, new DBColumn[] { id, pid, state});
        }
    }

    public static final class UserTable extends DBTable {

        private static final long serialVersionUID = 1L;

        public final DBTableColumn id;
        public final DBTableColumn login;

        public UserTable(DBDatabase db) {
            super("USERS", db);
            id = addColumn("ID", DataType.AUTOINC, 0, DataMode.AutoGenerated, "USERS_ID_SEQ");
            id.setBeanPropertyName("id");
            login = addColumn("LOGIN", DataType.TEXT, 255, true);
            login.setBeanPropertyName("login");
            setPrimaryKey(id);
            addIndex(String.format("%s_%s_IDX", getName(), login.getName()), true, new DBColumn[] { login });
        }

    }

    public class DigitalObjectTable extends DBTable {

        private static final long serialVersionUID = 1L;

        public final DBTableColumn id;
        public final DBTableColumn rUserId;
        public final DBTableColumn instance;
        public final DBTableColumn pid;
        public final DBTableColumn label;
        public final DBTableColumn parentPath;
        public final DBTableColumn parentLabel;
        public final DBTableColumn version;
        public final DBTableColumn datum;
        public final DBTableColumn updateTime;
        public final DBTableColumn state;
        public final DBTableColumn lock;
        public final DBTableColumn model;

        public DigitalObjectTable(DBDatabase db) {
            super("DIGITALOBJECT", db);
            id = addColumn("ID", DataType.AUTOINC, 0, DataMode.AutoGenerated, "DIGITALOBJECT_ID_SEQ");
            rUserId = addColumn("R_USER_ID", DataType.INTEGER, 0, true);
            instance = addColumn("INSTANCE", DataType.TEXT, 2000, true);
            pid = addColumn("PID", DataType.TEXT, 2000, true);
            version = addColumn("VERSION", DataType.TEXT, 255, true);
            datum = addColumn("DATUM", DataType.DATETIME, 0, true);
            updateTime = addColumn("UPDATE_TIME", DataType.TIMESTAMP, 0, true);
            state = addColumn("STATE", DataType.TEXT, 20, true);
            label = addColumn("LABEL", DataType.TEXT, 1024, false);
            parentPath = addColumn("PARENT_PATH", DataType.TEXT, 255, false);
            parentLabel = addColumn("PARENT_LABEL", DataType.TEXT, 255, false);
            model = addColumn("MODEL", DataType.TEXT, 255, false);
            lock = addColumn("LOCK", DataType.BOOL, 10, false);

            setPrimaryKey(id);
            addIndex("DIGITALOBJECT_USERPID_INDEX", true, new DBColumn[] { rUserId, pid });
        }

    }

    public AltoEditorDatabase() {

        addRelation(tableDigitalObject.rUserId.referenceOn(tableUser.id));
    }

    void init(EmpireConfiguration conf) throws SQLException {
        DBDatabaseDriver drv = conf.getDriver();
        Connection conn = conf.getConnection();
        open(drv, conn);
        try {
            int schemaVersion = schemaExists(this, conn);
            if (VERSION == schemaVersion) {
                return;
            }
            if (schemaVersion > 0) {
                schemaVersion = AltoEditorDatabaseV5.upgradeToVersion6(schemaVersion, this, conn, conf);
                if (schemaVersion != VERSION) {
                    LOG.error("Failed to upgrade schema to version " + VERSION + ".");
                    throw new SQLException("Failed to upgrade schema to version " + VERSION + ".");
                }
            } else {
                createSchema(this, conn);
            }
        } finally {
            conn.close();
        }
    }


    static int schemaExists(AltoEditorDatabase db, Connection c) {
        try {
            DBCommand cmd = db.createCommand();
            cmd.select(db.tableVersion.version);
            cmd.orderBy(db.tableVersion.version, true);
            cmd.limitRows(1);
            int version = db.querySingleInt(cmd, -1, c);
            return version;
        } catch (QueryFailedException ex) {
            return -1;
        }
    }

    private static void createSchema(AltoEditorDatabase db, Connection conn) throws SQLException {
        if (db.getDriver() instanceof DBDatabaseDriverPostgreSQL) {
            conn.setAutoCommit(true);
        }
        DBSQLScript script = new DBSQLScript();
        db.getCreateDDLScript(db.getDriver(), script);
        LOG.debug(script.toString());
        script.executeAll(db.getDriver(), conn);
        db.initVersion(conn);
        db.commit(conn);
        conn.setAutoCommit(false);
    }

    int initVersion(Connection conn) {
        AltoEditorDatabase db = this;
        DBRecord dbRecord = new DBRecord();

        dbRecord.create(db.tableVersion);
        dbRecord.setValue(db.tableVersion.version, VERSION);
        dbRecord.setValue(db.tableVersion.datum, new java.sql.Timestamp(System.currentTimeMillis()));
        dbRecord.update(conn);
        return VERSION;
    }
}
